name: Auto Sync Upstream
on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC时间 02:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_PAT }}
          fetch-depth: 0 

      - name: Smart Merge from huilang-me
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git remote add upstream https://github.com/huilang-me/CF-Server-Monitor.git
          git fetch upstream
          
          git merge upstream/main --strategy-option=ours -m "Auto sync upstream changes" || echo "No changes or handled merge."
          
          # 必须使用存在 SECRETS 里的具有 workflow 和 repo 权限的自定义 PAT 进行推流，才能彻底打通连带反应
          git remote set-url origin https://x-access-token:${{ secrets.SYNC_PAT }}@github.com/SKLDFHIENM/CF-Server-Monitor.git
          git push origin main
